<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQDhv3uu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQDhv3uu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQDhv3uu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQDhv3uu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQDhv3uu\App_KernelDevDebugContainer([
    'container.build_hash' => 'QDhv3uu',
    'container.build_id' => '68d529c3',
    'container.build_time' => 1623716246,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQDhv3uu');
